name = "Fib"
uuid = "2a827ddc-7381-4640-bb78-1d8875325a89"
authors = ["AK <ankar71gr@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
